# reindex the search
language: ruby
cache: bundler
before_install:
  - gem install bundler jekyll-algolia
script:
  - bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
