remote_theme: "mmistakes/minimal-mistakes@4.19.1"
readme_index:
  enabled: false
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
minimal_mistakes_skin: "sunrise"
title: "GemRB homepage"
masthead_title: "GemRB"
subtitle: "Infinity Engine redone"
description: "Home of GemRB, a portable open-source implementation of Bioware's Infinity Engine"
url: "https://gemrb.github.io"
repository: "gemrb/gemrb.github.io"
logo: "/assets/img/site/apple-touch-icon.png"
#og_image: "/assets/img/site/logo.png" 120x120px minimum
timezone: Europe/Ljubljana

footer:
  links:
    - label: "Forum"
      icon: "fab fa-fw fa-optin-monster"
      url: "https://www.gibberlings3.net/forums/forum/91-gemrb/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gemrb"


search: true
search_provider: algolia
exclude: [vendor]
algolia:
  application_id: "QZAOH9F6TU"
  index_name: "gemrb"
