name: CI

on:
  schedule:
    # once per month, midnight on the 1st
    - cron: 0 0 1 1/1 *

jobs:
  # This workflow contains a single job called "build"
  cname-pong:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Temporarily change CNAME
      run: sed -i 's,^.*$,www.gemrb.org,' CNAME

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Hack CNAME

    - name: Wait 10 min
      run: sleep 10m

    - name: restore CNAME
      run: sed -i 's,^.*$,gemrb.org,' CNAME

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Unhack CNAME
